name: Python Tests

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    # environment: staging
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.X
      uses: actions/setup-python@v3
      with:
        python-version: "3.X"
    # - name: Installing fritzbox-monitor package
    #   run: |
    #     python -m pip install -e .
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Running pytests
      run: |
        python -m pytest